"""add post_event_bill_path

Revision ID: 19c35031c7ba
Revises: 7c6559e7e4ea
Create Date: 2026-07-30 21:09:05.605338

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '19c35031c7ba'
down_revision = '7c6559e7e4ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_event_bill_path', sa.Text(length=16777215), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('post_event_bill_path')
    # ### end Alembic commands ###
