"""Added post_event_report_path

Revision ID: 219e23e7d6cb
Revises: 69f0fc1c34c1
Create Date: 2026-07-30 11:32:22.386347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '219e23e7d6cb'
down_revision = '69f0fc1c34c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_event_report_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('post_event_report_path')

    # ### end Alembic commands ###
