"""add event_category

Revision ID: 34ceffc5093e
Revises: 19c35031c7ba
Create Date: 2026-07-30 22:34:24.512306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34ceffc5093e'
down_revision = '19c35031c7ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_category', sa.String(length=50), server_default='Seminar/Workshop', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('event_category')

    # ### end Alembic commands ###
