"""change post_event_report_path to MEDIUMTEXT

Revision ID: 44b240954956
Revises: 219e23e7d6cb
Create Date: 2026-07-30 14:43:05.298156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44b240954956'
down_revision = '219e23e7d6cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('post_event_report_path',
               existing_type=sa.String(length=255),
               type_=sa.Text(length=16777215),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('post_event_report_path',
               existing_type=sa.Text(length=16777215),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
