"""change paths to MEDIUMTEXT

Revision ID: 7c6559e7e4ea
Revises: 3c5a5673d2bd
Create Date: 2026-07-30 19:32:35.576533

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7c6559e7e4ea'
down_revision = '3c5a5673d2bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('proposal_pdf_path',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(length=16777215),
               existing_nullable=True)
        batch_op.alter_column('budget_pdf_path',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(length=16777215),
               existing_nullable=True)
        batch_op.alter_column('supporting_docs_path',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(length=16777215),
               existing_nullable=True)
        batch_op.alter_column('post_event_report_path',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=16777215),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('post_event_report_path',
               existing_type=sa.Text(length=16777215),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
        batch_op.alter_column('supporting_docs_path',
               existing_type=sa.Text(length=16777215),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('budget_pdf_path',
               existing_type=sa.Text(length=16777215),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('proposal_pdf_path',
               existing_type=sa.Text(length=16777215),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
